# =================================================================================================================================
# Copyright (c) RapidField LLC. Licensed under the MIT License. See LICENSE.txt in the project root for license information.
# =================================================================================================================================

# This file defines rules which govern the behavior of the Mergify bot when evaluating pull requests.
# ---------------------------------------------------------------------------------------------------------------------------------

pull_request_rules:

# ---------------------------------------------------------------------------------------------------------------------------------
- name: Label new pull requests.
# ---------------------------------------------------------------------------------------------------------------------------------

  conditions:

  # Basic
  # ----------------------------------------------------------------
  - -closed
  - -merged

  # Stage
  # ----------------------------------------------------------------
  - label!=Stage-0-New
  - label!=Stage-1-UnderReview
  - label!=Stage-2-Accepted
  - label!=Stage-2-Deferred
  - label!=Stage-2-Rejected
  - label!=Stage-3-InProgress
  - label!=Stage-4-Complete

  # Verdict
  # ----------------------------------------------------------------
  - label!=Verdict-Pending
  - label!=Verdict-Relayed

  actions:

    label:
      add:
      - Stage-0-New
      - Verdict-Pending

# ---------------------------------------------------------------------------------------------------------------------------------
- name: Label uncategorized pull requests.
# ---------------------------------------------------------------------------------------------------------------------------------

  conditions:

  # Basic
  # ----------------------------------------------------------------
  - -closed
  - -merged

  # Category
  # ----------------------------------------------------------------
  - label!=Category-Defect
  - label!=Category-Feature
  - label!=Category-Maintenance
  - label!=Category-ProductionRelease
  - label!=Category-Question
  - label!=Category-Uncategorized

  # Stage
  # ----------------------------------------------------------------
  - label=Stage-0-New

  actions:

    label:
      add:
      - Category-Uncategorized

# ---------------------------------------------------------------------------------------------------------------------------------
- name: Label bot-sourced pull requests.
# ---------------------------------------------------------------------------------------------------------------------------------

  conditions:

  # Basic
  # ----------------------------------------------------------------
  - -closed
  - -merged

  # Identity
  # ----------------------------------------------------------------
  - author~=(^dependabot.*$)|(^mergify.*$)

  # Source
  # ----------------------------------------------------------------
  - label!=Source-Bot
  - label!=Source-Maintainer
  - label!=Source-User

  # Stage
  # ----------------------------------------------------------------
  - label=Stage-0-New

  actions:

    label:
      add:
      - Source-Bot

# ---------------------------------------------------------------------------------------------------------------------------------
- name: Label maintainer-sourced pull requests.
# ---------------------------------------------------------------------------------------------------------------------------------

  conditions:

  # Basic
  # ----------------------------------------------------------------
  - -closed
  - -merged

  # Identity
  # ----------------------------------------------------------------
  - author~=(^adamjstone$)

  # Source
  # ----------------------------------------------------------------
  - label!=Source-Bot
  - label!=Source-Maintainer
  - label!=Source-User

  # Stage
  # ----------------------------------------------------------------
  - label=Stage-0-New

  actions:

    label:
      add:
      - Source-Maintainer

# ---------------------------------------------------------------------------------------------------------------------------------
- name: Label user-sourced pull requests.
# ---------------------------------------------------------------------------------------------------------------------------------

  conditions:

  # Basic
  # ----------------------------------------------------------------
  - -closed
  - -merged

  # Source
  # ----------------------------------------------------------------
  - label!=Source-Bot
  - label!=Source-Maintainer
  - label!=Source-User

  # Stage
  # ----------------------------------------------------------------
  - label!=Stage-0-New
  - label=Stage-1-UnderReview

  actions:

    label:
      add:
      - Source-User

# ---------------------------------------------------------------------------------------------------------------------------------
- name: Label dependency management pull requests.
# ---------------------------------------------------------------------------------------------------------------------------------

  conditions:

  # Basic
  # ----------------------------------------------------------------
  - -closed
  - -merged

  # Identity
  # ----------------------------------------------------------------
  - author~=(^dependabot.*$)

  # Subcategory
  # ----------------------------------------------------------------
  - label!=Subcategory-Dependencies

  # Tag
  # ----------------------------------------------------------------
  - label!=Tag-AddReleaseNote

  actions:

    label:
      add:
      - Subcategory-Dependencies
      - Tag-AddReleaseNote

# ---------------------------------------------------------------------------------------------------------------------------------
- name: Label maintenance pull requests.
# ---------------------------------------------------------------------------------------------------------------------------------

  conditions:

  # Basic
  # ----------------------------------------------------------------
  - -closed
  - -merged

  # Category
  # ----------------------------------------------------------------
  - label!=Category-Maintenance
  - label=Category-Uncategorized

  # Identity
  # ----------------------------------------------------------------
  - author~=(^dependabot.*$)|(^mergify.*$)

  actions:

    label:
      add:
      - Category-Maintenance
      remove:
      - Category-Uncategorized

# ---------------------------------------------------------------------------------------------------------------------------------
- name: Label under-review pull requests.
# ---------------------------------------------------------------------------------------------------------------------------------

  conditions:

  # Basic
  # ----------------------------------------------------------------
  - -closed
  - -merged

  # Category
  # ----------------------------------------------------------------
  - label!=Category-Uncategorized

  # Stage
  # ----------------------------------------------------------------
  - label=Stage-0-New
  - label!=Stage-1-UnderReview
  - label!=Stage-2-Accepted
  - label!=Stage-2-Deferred
  - label!=Stage-2-Rejected

  # Status
  # ----------------------------------------------------------------
  - status-success=Summary

  actions:

    label:
      add:
      - Stage-1-UnderReview
      remove:
      - Stage-0-New

# ---------------------------------------------------------------------------------------------------------------------------------
- name: Label accepted maintenance pull requests.
# ---------------------------------------------------------------------------------------------------------------------------------

  conditions:

  # Basic
  # ----------------------------------------------------------------
  - -closed
  - -merged

  # Category
  # ----------------------------------------------------------------
  - label=Category-Maintenance

  # Identity
  # ----------------------------------------------------------------
  - base~=(^master$)|(^develop$)|(^release\/(.+)$)|(^feature\/(.+)$)|(^hotfix\/(.+)$)

  # Stage
  # ----------------------------------------------------------------
  - label=Stage-1-UnderReview
  - label!=Stage-2-Accepted
  - label!=Stage-2-Deferred
  - label!=Stage-2-Rejected

  # Status
  # ----------------------------------------------------------------
  - status-success=continuous-integration/appveyor/branch
  - status-success=Summary

  actions:

    label:
      add:
      - Stage-2-Accepted
      remove:
      - Stage-1-UnderReview

# ---------------------------------------------------------------------------------------------------------------------------------
- name: Label rejected pull requests.
# ---------------------------------------------------------------------------------------------------------------------------------

  conditions:

  # Basic
  # ----------------------------------------------------------------
  - closed
  - -merged

  # Stage
  # ----------------------------------------------------------------
  - label!=Stage-2-Accepted
  - label!=Stage-2-Deferred
  - label!=Stage-2-Rejected

  actions:

    label:
      add:
      - Stage-2-Rejected
      remove:
      - Stage-0-New
      - Stage-1-UnderReview
      - Stage-2-Accepted
      - Stage-2-Deferred
      - Stage-3-InProgress
      - Stage-4-Complete

# ---------------------------------------------------------------------------------------------------------------------------------
- name: Label in-progress pull requests when the author is trusted.
# ---------------------------------------------------------------------------------------------------------------------------------

  conditions:

  # Basic
  # ----------------------------------------------------------------
  - -closed
  - -merged

  # Identity
  # ----------------------------------------------------------------
  - author~=(^adamjstone$)|(^dependabot.*$)|(^mergify.*$)
  - base~=(^master$)|(^develop$)|(^release\/(.+)$)|(^feature\/(.+)$)|(^hotfix\/(.+)$)

  # Stage
  # ----------------------------------------------------------------
  - label=Stage-2-Accepted
  - label!=Stage-2-Deferred
  - label!=Stage-2-Rejected
  - label!=Stage-3-InProgress

  # Status
  # ----------------------------------------------------------------
  - status-success=continuous-integration/appveyor/branch
  - status-success=Summary

  actions:

    label:
      add:
      - Stage-3-InProgress
      remove:
      - Stage-2-Accepted

# ---------------------------------------------------------------------------------------------------------------------------------
- name: Label in-progress pull requests when reviewed and approved.
# ---------------------------------------------------------------------------------------------------------------------------------

  conditions:

  # Basic
  # ----------------------------------------------------------------
  - -closed
  - -merged

  # Identity
  # ----------------------------------------------------------------
  - "#approved-reviews-by>=1"
  - base~=(^feature\/(.+)$)|(^hotfix\/(.+)$)

  # Stage
  # ----------------------------------------------------------------
  - label=Stage-2-Accepted
  - label!=Stage-2-Deferred
  - label!=Stage-2-Rejected
  - label!=Stage-3-InProgress

  # Status
  # ----------------------------------------------------------------
  - status-success=continuous-integration/appveyor/branch
  - status-success=Summary

  actions:

    label:
      add:
      - Stage-3-InProgress
      remove:
      - Stage-2-Accepted

# ---------------------------------------------------------------------------------------------------------------------------------
- name: Label completed pull requests.
# ---------------------------------------------------------------------------------------------------------------------------------

  conditions:

  # Basic
  # ----------------------------------------------------------------
  - closed
  - merged

  # Stage
  # ----------------------------------------------------------------
  - label!=Stage-4-Complete

  actions:

    label:
      add:
      - Stage-4-Complete
      remove:
      - Stage-0-New
      - Stage-1-UnderReview
      - Stage-2-Accepted
      - Stage-2-Deferred
      - Stage-2-Rejected
      - Stage-3-InProgress

# ---------------------------------------------------------------------------------------------------------------------------------
- name: Label completed backmerge pull requests.
# ---------------------------------------------------------------------------------------------------------------------------------

  conditions:

  # Basic
  # ----------------------------------------------------------------
  - closed
  - merged

  # Identity
  # ----------------------------------------------------------------
  - author~=(^mergify.*$)
  - title~=(^.*\(bp .*\)$)

  # Stage
  # ----------------------------------------------------------------
  - label=Stage-4-Complete

  # Verdict
  # ----------------------------------------------------------------
  - label=Verdict-Pending
  - label!=Verdict-Relayed

  actions:

    label:
      add:
      - Verdict-Relayed
      remove:
      - Verdict-Pending

# ---------------------------------------------------------------------------------------------------------------------------------
- name: Merge eligible pull requests.
# ---------------------------------------------------------------------------------------------------------------------------------

  conditions:

  # Basic
  # ----------------------------------------------------------------
  - -closed
  - -merged

  # Stage
  # ----------------------------------------------------------------
  - label!=Stage-2-Accepted
  - label!=Stage-2-Deferred
  - label!=Stage-2-Rejected
  - label=Stage-3-InProgress
  - label!=Stage-4-Complete

  # Status
  # ----------------------------------------------------------------
  - status-success=continuous-integration/appveyor/branch
  - status-success=continuous-integration/appveyor/pr
  - status-success=Summary

  actions:

    merge:
      method: merge

# ---------------------------------------------------------------------------------------------------------------------------------
- name: Backmerge from master when the author is trusted.
# ---------------------------------------------------------------------------------------------------------------------------------

  conditions:

  # Basic
  # ----------------------------------------------------------------
  - closed
  - merged

  # Identity
  # ----------------------------------------------------------------
  - author~=(^adamjstone$)|(^dependabot.*$)|(^mergify.*$)
  - base=master

  # Stage
  # ----------------------------------------------------------------
  - label!=Stage-2-Accepted
  - label!=Stage-2-Deferred
  - label!=Stage-2-Rejected
  - label!=Stage-3-InProgress
  - label=Stage-4-Complete

  # Tag
  # ----------------------------------------------------------------
  - label!=Tag-Backmerged

  actions:

    backport:
      branches:

      # Persistent
      # ----------------------------------------------------------------
      - admin
      - develop

      # Release
      # ----------------------------------------------------------------
      - release/v1.0.25-preview1
      - release/v1.0.26-preview1

    label:
      add:
      - Tag-Backmerged

# ---------------------------------------------------------------------------------------------------------------------------------
- name: Backmerge from develop when the author is trusted.
# ---------------------------------------------------------------------------------------------------------------------------------

  conditions:

  # Basic
  # ----------------------------------------------------------------
  - closed
  - merged

  # Identity
  # ----------------------------------------------------------------
  - author~=(^adamjstone$)|(^dependabot.*$)|(^mergify.*$)
  - base=develop

  # Stage
  # ----------------------------------------------------------------
  - label!=Stage-2-Accepted
  - label!=Stage-2-Deferred
  - label!=Stage-2-Rejected
  - label!=Stage-3-InProgress
  - label=Stage-4-Complete

  # Tag
  # ----------------------------------------------------------------
  - label!=Tag-Backmerged

  actions:

    backport:
      branches:

      # Feature
      # ----------------------------------------------------------------
      - feature/0007-rabbitmq-support
      - feature/0012-structuremap-support

    label:
      add:
      - Tag-Backmerged