# =================================================================================================================================
# Copyright (c) RapidField LLC. Licensed under the MIT License. See LICENSE.txt in the project root for license information.
# =================================================================================================================================
pull_request_rules:
# ---------------------------------------------------------------------------------------------------------------------------------
- name: Label new Mergify pull requests.
  conditions:
  - author=mergify[bot]
  - -closed
  - -merged
  actions:
    label:
      add:
      - Category-Maintenance
      - Stage0-New
      - Subcategory-Delivery
      - Verdict-Pending
# ---------------------------------------------------------------------------------------------------------------------------------
- name: Label completed pull requests.
  conditions:
  - closed
  - label!=Stage4-Complete
  - merged
  - status-success=continuous-integration/appveyor/pr
  actions:
<<<<<<< HEAD
=======
    comment:
      message: This pull request is merged! (Testing Mergify)
>>>>>>> 3e5663b... Testing Mergify.
    label:
      add:
      - Stage4-Complete
      remove:
      - Stage0-New
      - Stage1-UnderReview
      - Stage2-Accepted
      - Stage2-Deferred
      - Stage2-Rejected
      - Stage3-InProgress
# ---------------------------------------------------------------------------------------------------------------------------------
- name: Merge to master when the author is trusted.
  conditions:
  - author~=(^adamjstone$)|(^dependabot\[bot\]$)|(^mergify\[bot\]$)
  - base=master
  - -closed
  - label!=Stage2-Rejected
  - -merged
  - status-success=continuous-integration/appveyor/pr
  actions:
    merge:
      method: merge
      strict: smart
# ---------------------------------------------------------------------------------------------------------------------------------
- name: Merge to develop when the author is trusted.
  conditions:
  - author~=(^adamjstone$)|(^dependabot\[bot\]$)|(^mergify\[bot\]$)
  - base=develop
  - -closed
  - label!=Stage2-Rejected
  - -merged
  - status-success=continuous-integration/appveyor/pr
  actions:
    merge:
      method: merge
      strict: smart
# ---------------------------------------------------------------------------------------------------------------------------------
- name: Merge to feature and hotfix branches when the author is trusted.
  conditions:
  - author~=(^adamjstone$)|(^dependabot\[bot\]$)|(^mergify\[bot\]$)
  - base~=^feature\/(.+)|hotfix\/(.+)
  - -closed
  - label!=Stage2-Rejected
  - -merged
  - status-success=continuous-integration/appveyor/pr
  actions:
    merge:
      method: merge
      strict: smart
# ---------------------------------------------------------------------------------------------------------------------------------
- name: Merge to feature and hotfix branches when reviewed and approved.
  conditions:
  - "#approved-reviews-by>=1"
  - base~=^feature\/(.+)|hotfix\/(.+)
  - -closed
  - label!=Stage2-Rejected
  - -merged
  - status-success=continuous-integration/appveyor/pr
  actions:
    merge:
      method: merge
      strict: smart
# ---------------------------------------------------------------------------------------------------------------------------------
- name: Backport from master when the author is trusted.
  conditions:
  - author~=(^adamjstone$)|(^dependabot\[bot\]$)|(^mergify\[bot\]$)
  - base=master
  - merged
  - status-success=continuous-integration/appveyor/pr
  actions:
    backport:
      branches: # List active hotfix and release branches here, along with develop.
      # -------------------------------------------------------------------------------------------
      - develop
      - release/v1.0.25-preview1
      - release/v1.0.26-preview1
<<<<<<< HEAD
=======
      # -------------------------------------------------------------------------------------------
    comment:
      message: Merging and backporting this pull request. (Testing Mergify)
    label:
      add:
      - Stage3-InProgress
      remove:
      - Stage0-New
      - Stage1-UnderReview
      - Stage2-Accepted
      - Stage2-Rejected
      - Stage4-Complete
    merge:
      method: merge
      strict: true
>>>>>>> 3e5663b... Testing Mergify.
# ---------------------------------------------------------------------------------------------------------------------------------
- name: Backport from develop when the author is trusted.
  conditions:
  - author~=(^adamjstone$)|(^dependabot\[bot\]$)|(^mergify\[bot\]$)
  - base=develop
  - merged
  - status-success=continuous-integration/appveyor/pr
  actions:
    backport:
      branches: # List active feature branches here.
      # -------------------------------------------------------------------------------------------
      - feature/0007_rabbitmq-support
      - feature/0012_structuremap-support
<<<<<<< HEAD
      - feature/0053_complex-string-extensions
      - feature/0055_complex-rng-extensions
# ---------------------------------------------------------------------------------------------------------------------------------
=======
      # -------------------------------------------------------------------------------------------
    comment:
      message: Merging and backporting this pull request. (Testing Mergify)
    label:
      add:
      - Stage3-InProgress
      remove:
      - Stage0-New
      - Stage1-UnderReview
      - Stage2-Accepted
      - Stage2-Rejected
      - Stage4-Complete
    merge:
      method: merge
      strict: true
# ---------------------------------------------------------------------------------------------------------------------------------
>>>>>>> 3e5663b... Testing Mergify.
