# =================================================================================================================================
# Copyright (c) RapidField LLC. Licensed under the MIT License. See LICENSE.txt in the project root for license information.
# =================================================================================================================================
pull_request_rules:
# --------------------------------------------------------------------------------------------------------------------------------- # test-2
- name: Label merged pull requests.
  conditions:
  - label=Stage3-InProgress
  - merged
  actions:
    comment:
      message: This pull request has been merged!
    label:
      add:
      - Stage4-Complete
      remove:
      - Stage3-InProgress
# ---------------------------------------------------------------------------------------------------------------------------------
- name: Label Mergify pull requests.
  conditions:
  - author=mergify[bot]
  actions:
    label:
      add:
      - Category-Maintenance
      - Stage0-New
      - Verdict-Pending
# ---------------------------------------------------------------------------------------------------------------------------------
- name: Merge and backport from master when the author is trusted.
  conditions:
  - author=adamjstone
  - base=master
  - label=Stage0-New
  - status-success=continuous-integration/appveyor/pr
  actions:
    backport:
      branches: # List active hotfix and release branches here, along with develop.
      # -------------------------------------------------------------------------------------------
      - develop
      - release/v1.0.25-preview1
      - release/v1.0.26-preview1
      # -------------------------------------------------------------------------------------------
    comment:
      message: Merging and backporting this pull request.
    label:
      add:
      - Stage3-InProgress
      remove:
      - Stage0-New
    merge:
      method: merge
      strict: true
# ---------------------------------------------------------------------------------------------------------------------------------
- name: Merge and backport from develop when the author is trusted.
  conditions:
  - author~=^adamjstone|dependabot\[bot\]|mergify\[bot\]
  - base=develop
  - label=Stage0-New
  - status-success=continuous-integration/appveyor/pr
  actions:
    backport:
      branches: # List active feature branches here.
      # -------------------------------------------------------------------------------------------
      - feature/0007_rabbitmq-support
      - feature/0012_structuremap-support
      # -------------------------------------------------------------------------------------------
    comment:
      message: Merging and backporting this pull request.
    label:
      add:
      - Stage3-InProgress
      remove:
      - Stage0-New
    merge:
      method: merge
      strict: true
# ---------------------------------------------------------------------------------------------------------------------------------
