# =================================================================================================================================
# Copyright (c) RapidField LLC. Licensed under the MIT License. See LICENSE.txt in the project root for license information.
# =================================================================================================================================

# This file controls automated CI/CD activity via AppVeyor.

# Version definition
version: 1.0.25+{build}

# Artifact definitions
artifacts:
- path: artifacts\Release
  name: ReleasePackages
- path: artifacts\_DocumentationWebsite
  name: DocumentationWebsite

# Build script
build_script:
- ps: .\Build.ps1

# Deployment settings
deploy: off

# Environment variables
environment:
  CODECOV_TOKEN:
    secure: 7/8LlzRGKOUWnZwRUPiZjaw1ugVc9OsFebsLdIA/mbbVintw7IhTOqT/fu31eTz3
  DOCWEB_FTP_PASSWORD:
    secure: IeMo53dCxMhfdS0Ul10w8VgFAz5voNHjVj7NcJcdGAfFrrxoTrqwFH7URO+tGWyFuTSdJzvH8woYilq+VTFb1Q==
  DOCWEB_FTP_USERNAME:
    secure: tpUXWb8YbSH2xVJ1tPbf/SMJN/WDuEi68NFDx3I/Luz6UtPoEwQhBgZuP6a8hbWbE56qxq31RqbPZhO9U09Upw==
  RAPIDFIELD_CSCERTKEY:
    secure: doWiHasUlfcfGw28sVQzAgx3gJFCCSAtf6+gTuuJmiOrrf7GOywK44WCVQPIcCQ8
  RAPIDFIELD_CSCERTKEY_SALT:
    secure: 1OEDzCm/yyUUnPtE7KDICqcUnOYhHhj4SPKlHsb4N2CMt+CSz4sWVksivKCeRtGVvUgI3qK7dfikGp49h8SijQ==
  RAPIDFIELD_CSCERTPWD:
    secure: NP2Ypdw2exl80s+hIKV6huknLTuPXrMzIj6kByUTegETh9k/ZF47muztJQKC1BPG
  RAPIDFIELD_NUGETAPIKEY:
    secure: aw6CkcahgF2ERsHRz/LMAKRPSkexSjAO/DM8SQA7T62vfQA+KDErlplDCA+BWEZN

# Visual Studio image
image: Visual Studio 2019

# Test settings
test: off