# =================================================================================================================================
# Copyright (c) RapidField LLC. Licensed under the MIT License. See LICENSE.txt in the project root for license information.
# =================================================================================================================================
version: 1.0.24-preview1.{build}
artifacts:
- path: artifacts\Release
  name: ReleasePackages
- path: artifacts\_DocumentationWebsite
  name: DocumentationWebsite
build_script:
- ps: .\Build.ps1
deploy:
- active_mode: true
  application: DocumentationWebsite
  artifact: DocumentationWebsite
  host: waws-prod-sn1-143.ftp.azurewebsites.windows.net/site/wwwroot
  on:
    branch: master
  password:
    secure: 6waa1SXgMW3RRH/oTntGQctSsvmtRSibqov05sr+2gQiVNCeiogQf3bWycsH5VWzrz1j3w4BWUI0YY1hBnYcyA==
  protocol: ftps
  provider: FTP
  username: SolidInstruments-DocWeb-App\$SolidInstruments-DocWeb-App
environment:
  RAPIDFIELD_CSCERTKEY:
    secure: 2UnQ5nbiA4U959m61TBLh1vI6/WDt08mN9E5+4h3FsFES7f3CZIJHciIMFWE/Nwn
  RAPIDFIELD_CSCERTPWD:
    secure: igzgdjN7Km8z/cVwEjnyd2Pjq8yF5v5UJym7Zd0r1p4ALkfiadpn0qCdvTGKKFwv
  RAPIDFIELD_NUGETAPIKEY:
    secure: +MUxngO910jKz1/jjAh6a5y8O0AujDeYNhKSfjiDBh6OISt1LQlNjXLPqn/OHV8n
image: Visual Studio 2017
test: off