version: 1.0.23-preview1.{build}
artifacts:
- path: artifacts\Release
  name: ReleaseArtifacts
- path: artifacts\Release\_DocumentationWebsite
  name: DocumentationWebsite
build_script:
- ps: .\Build.ps1
deploy:
- provider: WebDeploy
  server: waws-prod-sn1-143.ftp.azurewebsites.windows.net/site/wwwroot
  website: www.solidinstruments.com
  username: SolidInstruments-DocWeb-App\$SolidInstruments-DocWeb-App
  password:
    secure: YIUFDGQnnNvw72yX/Cp+c5HPUIDs2Jj38TqF2vjL5YGhjMFKr8JOyU6UkztYLgq9Rd+eRBN8KF8KENcIMSOTUg==
  artifact: DocumentationWebsite
  remove_files: true
  on:
    branch: master
image: Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
test: off