version: 1.0.23-preview1.{build}
artifacts:
- path: artifacts\Release
  name: ReleasePackages
- path: artifacts\_DocumentationWebsite
  name: DocumentationWebsite
build_script:
- ps: .\Build.ps1
deploy:
- application: DocumentationWebsite
  artifact: DocumentationWebsite
  host: waws-prod-sn1-143.ftp.azurewebsites.windows.net/site/wwwroot
  on:
    branch: master
  password:
    secure: 6waa1SXgMW3RRH/oTntGQctSsvmtRSibqov05sr+2gQiVNCeiogQf3bWycsH5VWzrz1j3w4BWUI0YY1hBnYcyA==
  protocol: ftps
  provider: FTP
  username: SolidInstruments-DocWeb-App\$SolidInstruments-DocWeb-App
environment:
  RAPIDFIELD_CSCERTKEY:
    secure: I1U8lEb/IgS9fSS8eBmb5mTZHkJsiMSOG3+ryrg30+mQa/UcvhUmt0Fo7Z3rCbrB
image: Visual Studio 2017
test: off