# =================================================================================================================================
# Copyright (c) RapidField LLC. Licensed under the MIT License. See LICENSE.txt in the project root for license information.
# =================================================================================================================================

# This file configures code coverage reporting via Codecov.
# =================================================================================================================================

# Basic
# =================================================================================================================================
codecov:
  branch: master
  notify:
    require_ci_to_pass: yes

# Bot commenting
# =================================================================================================================================
comment:
  layout: "reach, diff"
  behavior: default
  require_changes: no

# Coverage calculation
# =================================================================================================================================
coverage:
  precision: 0
  round: down
  range: "30...70"
  status:
    changes: off
    patch: off
    project:
      default:
        base: auto
        target: auto
        threshold: 1

# Ignored paths
# =================================================================================================================================
ignore:
  - "cicd/**"
  - "example/**"
  - "test/**"

# Parsing
# =================================================================================================================================
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no