# =================================================================================================================================
# Copyright (c) RapidField LLC. Licensed under the MIT License. See LICENSE.txt in the project root for license information.
# =================================================================================================================================

# This file configures code coverage reporting via Codecov.
# ---------------------------------------------------------------------------------------------------------------------------------

codecov:
  branch: master
  notify:
    require_ci_to_pass: yes

comment:
  layout: "reach, diff"
  behavior: default
  require_changes: no

coverage:
  precision: 0
  round: down
  range: "30...70"
  status:
    changes: off
    patch: off
    project:
      default:
        base: auto
        target: auto
        threshold: 1

ignore:
  - "cicd/**"
  - "example/**"
  - "test/**"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
